apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    rc: nginx-test-rc
  name: nginx-test-rc
spec:
  replicas: 2
  selector:
    app: nginx-test-pod
  template:
    metadata:
      labels:
        app: nginx-test-pod
    spec:
      containers:
      - name: nginx
        image: nginx
